name: Ubuntu (build-&-test)

on:
  push:
    branches: 
      - master 
      - develop
  pull_request:
    branches: 
      - master 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          make init

      - name: Install Unix dependencies 
        run: |
          sudo apt-get install time libunwind8-dev g++-9 gcc-9
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9

      - name: Install Perun
        run: |
          make install
          perun --help

      - name: Prepare test enviroment
        run: |
          git config --global user.email "perun-allmighty@gmail.com"
          git config --global user.name "Perun Allmighty"

      - name: Run tests
        run: |
          make test
          codecov

      - name: Generate docs
        run: |
          make docs
